### ISSUE TITLE
client does not properly send streaming requests

### ISSUE THREAD

**Issue by hawkw** [tower-rs/tower-grpc#16]
I've run into some issues that suggest a probable bug in `tower-grpc` while working on implementing the [`client_streaming`](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#client_streaming) interoperability test case. 

This test has the client call a client streaming RPC, sends multiple payloads, and then await a unary response, while the server aggregates the number of bytes received from the client and sends that value in the response. The client then asserts that the server received the correct number of bytes.

Here's the relevant code in the client implementation:

https://github.com/tower-rs/tower-grpc/blob/6a7ce4077200080cbd47b2bb6e209b087316a653/tower-grpc-examples/src/interop/client.rs#L390-L416

When I run the `tower-grpc` test client against `grpc-go`'s interop server, the test fails at the assertion that the bytes aggregated value returned by the server is correct:
```
client_streaming:
  ✔ call must be successful
  ✖ aggregated payload size must be 74922 bytes
  in `response.aggregated_payload_size == 74922`: aggregated_payload_size=0
```

Interestingly, when I run the same test against `grpc-java`'s test server, the server returns an error, and prints the following stack trace to the console:
```
Jan 03, 2018 12:55:27 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@3ac811
io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
	at io.grpc.Status.asRuntimeException(Status.java:517)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:168)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:82)
	at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:287)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:251)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:624)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:105)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readTag(CodedInputStream.java:609)
	at com.google.protobuf.BoolValue.<init>(BoolValue.java:43)
	at com.google.protobuf.BoolValue.<init>(BoolValue.java:14)
	at com.google.protobuf.BoolValue$1.parsePartialFrom(BoolValue.java:453)
	at com.google.protobuf.BoolValue$1.parsePartialFrom(BoolValue.java:448)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:874)
	at io.grpc.testing.integration.Messages$StreamingInputCallRequest.<init>(Messages.java:4867)
	at io.grpc.testing.integration.Messages$StreamingInputCallRequest.<init>(Messages.java:4809)
	at io.grpc.testing.integration.Messages$StreamingInputCallRequest$1.parsePartialFrom(Messages.java:5666)
	at io.grpc.testing.integration.Messages$StreamingInputCallRequest$1.parsePartialFrom(Messages.java:5661)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parseFrom(ProtoLiteUtils.java:173)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:165)
	... 9 more
```

This leads me to suspect the request messages are being encoded improperly?

**Comment by olix0r** [comment]
it would probably be helpful to capture tshark output for such a stream

**Comment by hawkw** [comment]
@olix0r here's the tshark capture from running the test against grpc-go:
https://gist.github.com/hawkw/fa7b7bc9d385f171bc4b832cd3a392e8

i haven't actually looked at the capture yet, but I'm planning to.

**Comment by hawkw** [comment]
looks like the client sends the following:
1. a series of data frames with lengths 16,384 and 10,807
   -  these frames have a combined length of 27,191 bytes, which seems correct to me - the first payload in the request frame should have a body of 27,182 bytes.
2. a data frame with length 15 and one with length 1,836
   - this also seems correct for the second two messages in the request stream, the one with a body of 8 bytes and the one with a body of 1828 bytes
2. two data frames with length 16,384 followed by one with length 3,725
   - this has a total length of 36,493 bytes, which is a bit shorter than the last message in the request stream (45,904 bytes), unless i'm missing something
3. then there's a window update
4. the server sends a trailers frame with `grpc-status: 0` and the response message
5. stream exits gracefully

so as far as I can tell, it looks like we are, at least, sending close to the right amount of payload data in the request stream (even though it looks like we may be missing part of the final message somewhere?); even though the server might not be seeing the correct amount of bytes, it doesn't seem like it should be seeing _zero_ bytes?
